### ISSUE TITLE
Empty result on 404

### ISSUE THREAD

**Issue by erhant** [andthattoo/ollama-workflows#10]
I'm running some tests, and it seems I get empty result when Ollama responds with 404, i.e. when I get the following log from Ollama during an execution:

```sh
[GIN] 2024/08/14 - 11:12:37 | 404 |     478.541µs |       127.0.0.1 | POST     "/api/chat"
```

the string output of executor is empty string.

Still looking into it, may have to do with my local Ollama version (which prompts an update since the release of llama3.1), in that case it could be nice to check Ollama version and prompt the user from within this crate as well.

**Comment by andthattoo** [comment]
might add some handling for this

**Comment by erhant** [comment]
Updated to latest Ollama (0.3.6) and issue persists.

Interestingly, it happens on OpenAI models as well, I only get results using `Phi3Mini` right now from among the models I've tried. Will try running the tests using this repo instead of my own tests see if its related to my code perhaps.

**Comment by erhant** [comment]
Yea its probably related to my part, but quite magical. I'm literally running the same test on my repo & on my fork of ollama-workfllows, one of them works other does not.

```rs
#[tokio::test]
async fn test_generation() {
    dotenv().ok();
    let env = Env::default().filter_or("LOG_LEVEL", "info");
    env_logger::Builder::from_env(env).init();
    let exe = Executor::new(Model::GPT4o);
    let workflow = Workflow::new_from_json("./tests/test_workflows/generation.json").unwrap();
    let mut memory = ProgramMemory::new();
    let input = Entry::try_value_or_str("What is 2 + 2?");
    let output = exe.execute(Some(&input), workflow, &mut memory).await;
    println!("Output: {:?}", output);
}
```

I will delve a bit more on why this may be the case, will close the issue after that.

P.S. the generation workflow:

```json
{
  "name": "LLM generation",
  "description": "Directly generate text with input",
  "config": {
    "max_steps": 1,
    "max_time": 50,
    "tools": [""]
  },
  "external_memory": {
    "context": [""],
    "question": [""],
    "answer": [""]
  },
  "tasks": [
    {
      "id": "A",
      "name": "Generate",
      "description": "",
      "prompt": "{text}",
      "inputs": [
        {
          "name": "text",
          "value": {
            "type": "input",
            "key": ""
          },
          "required": true
        }
      ],
      "operator": "generation",
      "outputs": [
        {
          "type": "write",
          "key": "result",
          "value": "__result"
        }
      ]
    },
    {
      "id": "__end",
      "name": "end",
      "description": "End of the task",
      "prompt": "End of the task",
      "inputs": [],
      "operator": "end",
      "outputs": []
    }
  ],
  "steps": [
    {
      "source": "A",
      "target": "__end"
    }
  ],
  "return_value": {
    "input": {
      "type": "read",
      "key": "result"
    }
  }
}

```

**Comment by erhant** [comment]
ah lol it turns out its just basic "api key not found" (for OpenAI) and "model not pulled" (for Ollama), but executor returns empty string.

> might add some handling for this

agreed, I guess its best if it returns `Result<String>` instead?
